fileVersion: 1
id: "3"
mappingDefinitions:
  BRONZE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  BRONZE_SAP:
    database: ""
    schema: ""
  BRONZE_UKG:
    database: ""
    schema: ""
  GOLD:
    database: COALESCE_PROD
    schema: GOLD
  SILVER:
    database: COALESCE_PROD
    schema: SILVER
name: Production
type: Environment
